FROM node:16 AS build

# Set working directory
WORKDIR /app

# Copy frontend files
COPY almaghribi/frontend/package.json almaghribi/frontend/package-lock.json ./
RUN npm install

COPY almaghribi/frontend/ .
RUN npm run build