services:
  jellyfin-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jellyfin-backend
    volumes:
      - config:/config
      - cache:/cache
      - /home/mohamed/media:/media
    ports:
      - "8096:8096"   # HTTP
      - "8920:8920"   # HTTPS
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://${JELLYFIN_HOST:-localhost}
      - JELLYFIN_FFmpegPath=/usr/bin/ffmpeg
      - JELLYFIN_ServiceName=jellyfin
      - JELLYFIN_DataDir=/config
      - JELLYFIN_CacheDir=/cache
      - JELLYFIN_LogDir=/config/log
      - JELLYFIN_HOST_WEB_CLIENT=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jellyfin-network

  jellyfin-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: jellyfin-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - jellyfin-backend
    networks:
      - jellyfin-network

volumes:
  config:
  cache:

networks:
  jellyfin-network:
    driver: bridge