version: "3.8"

services:
  jellyfin-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: jellyfin-backend
    volumes:
      - config:/config
      - cache:/cache
      - /home/mohamed/media:/media
    ports:
      - "8096:8096"   # HTTP
      - "8920:8920"   # HTTPS
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://${JELLYFIN_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jellyfin-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: jellyfin-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - jellyfin-backend

volumes:
  config:
  cache: