services:
  media-server:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: media-server
    volumes:
      - media-server-config:/config
      - media-server-cache:/cache
      - /home/mohamed/media:/media
    ports:
      - "8096:8096"   # HTTP (includes web client)
      - "8920:8920"   # HTTPS (includes web client)
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://${MEDIA_SERVER_HOST:-localhost}
      - JELLYFIN_FFmpegPath=/usr/bin/ffmpeg
      - JELLYFIN_ServiceName=media-server
      - JELLYFIN_CONFIG_DIR=/config
      - JELLYFIN_DATA_DIR=/config/data
      - JELLYFIN_CACHE_DIR=/cache
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_WEB_DIR=/app/jellyfin-web
      - JELLYFIN_HOST_WEB_CLIENT=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - media-server-network

networks:
  media-server-network:
    driver: bridge

volumes:
  media-server-config:
  media-server-cache: