services:
  jellyfin:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: jellyfin
    volumes:
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - /home/mohamed/media:/media
    ports:
      - "8096:8096"   # HTTP (includes web client)
      - "8920:8920"   # HTTPS (includes web client)
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://${JELLYFIN_HOST:-localhost}
      - JELLYFIN_FFmpegPath=/usr/bin/ffmpeg
      - JELLYFIN_ServiceName=jellyfin
      - JELLYFIN_DataDir=/config
      - JELLYFIN_CacheDir=/cache
      - JELLYFIN_LogDir=/config/log
      - JELLYFIN_HOST_WEB_CLIENT=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jellyfin-network

networks:
  jellyfin-network:
    driver: bridge